### ISSUE TITLE
代码模块缺少

### ISSUE THREAD

**Issue by code4luck** [Edapinenut/GeoAB#1]
非常感谢大佬您的开源，很优秀的工作，但是在运行代码时我发现缺少了一些模块，utils，data模块以及dataset中提到的一些函数您能补上么？感谢。

**Comment by EDAPINENUT** [comment]
感谢 follow 我们的工作。当时可能是git ignore没写好。 已经将两份文件重新补齐。 如果有什么开源上的问题，欢迎及时提出。

**Comment by code4luck** [comment]
> 感谢 follow 我们的工作。当时可能是git ignore没写好。 已经将两份文件重新补齐。 如果有什么开源上的问题，欢迎及时提出。

大佬这边重新下载SAbdad数据在进行预处理部分您数据代码好像有点不太全，能补一下么？还是说这些数据的预处理直接使用dyMEAN的预处理脚本就行呢？因为我看pdb_utils好像是有一些区别的。麻烦了，感谢。

**Comment by EDAPINENUT** [comment]
预处理的代码就是dymean的脚本。 pdb_utils里的是torch.dataloader.dataset继承的内容，在预处理的时候基本不会调用。

google drive中的zip文件应该是可以直接使用的。

**Comment by code4luck** [comment]
> 预处理的代码就是dymean的脚本。 pdb_utils里的是torch.dataloader.dataset继承的内容，在预处理的时候基本不会调用。
> 
> google drive中的zip文件应该是可以直接使用的。

好的感谢。🎈

**Comment by EDAPINENUT** [comment]
The issue has been addressed. If there is any other question, please contact me through my e-mail or the github issue platform. Thanks.
